(function(g){var window=this;var Z5=function(a,b,c){a.w.set(b,c)},$5=function(a){Z5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},a6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.Im(a.w,b,c)},Aua=function(a,b){var c=[];
g.Qj(b,function(d){try{var e=g.Ln.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Kn(e)&&c.push(d)},a);
return c},Bua=function(a,b){var c=Aua(a,b);
(0,g.x)(c,function(d){g.Ln.prototype.remove.call(this,d)},a)},Cua=function(a){if(a.Xc){if(a.Xc.locationOverrideToken)return{locationOverrideToken:a.Xc.locationOverrideToken};
if(null!=a.Xc.latitudeE7&&null!=a.Xc.longitudeE7)return{latitudeE7:a.Xc.latitudeE7,longitudeE7:a.Xc.longitudeE7}}return null},Dua=function(a,b){g.cb(a,b)||a.push(b)},Eua=function(a,b){var c=b instanceof g.Zb?b:g.dc(b,/^data:image\//i.test(b));
a.src=g.ac(c)},b6=function(){},Fua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Gua=function(a,b,c,d){var e=new g.xm(null,void 0);
a&&g.ym(e,a);b&&g.zm(e,b);c&&g.Am(e,c);d&&(e.u=d);return e},c6=function(a,b){g.xo[a]=!0;
var c=g.vo();c&&c.publish.apply(c,arguments);g.xo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.tm;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Hua(this,a.capabilities||""),Iua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Hua=function(a,b){a.capabilities.clear();
(0,g.ce)(b.split(","),g.Ta(g.y.contains,Jua)).forEach(function(c){a.capabilities.add(c)})},Iua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Kua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Lua=function(a){return new e6(a)},Mua=function(a){return g.Na(a)?(0,g.ic)(a,Lua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Na(a)?"["+(0,g.ic)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Nua=function(a){return(0,g.ic)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.$a(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.Xr)(),c=(0,g.Wr)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Oua=function(){var a=(0,g.Wr)();
a&&Bua(a,a.o.lf(!0))},m6=function(){var a=g.Zr("yt-remote-connected-devices")||[];
g.tb(a);return a},Pua=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ic)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Qua=function(a){g.Yr("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.Zr("yt-remote-device-id");a||(a=i6(),g.Yr("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.cb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.cb(a,b);g.$r()&&g.vb(a,b);a=Pua(a);if(g.db(a))try{g.lq("remote_sid")}catch(c){}else try{g.jq("remote_sid",a.join(","),-1)}catch(c){}},Rua=function(){return g.Zr("yt-remote-session-browser-channel")},Sua=function(){return g.Zr("yt-remote-local-screens")||[]},Tua=function(){g.Yr("yt-remote-lounge-token-expiration",!0,86400)},Uua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ic)(Sua(),function(d){return d.loungeToken}),c=(0,g.ic)(a,function(d){return d.loungeToken});
(0,g.bi)(c,function(d){return!g.cb(b,d)})&&Tua();
g.Yr("yt-remote-local-screens",a,31536E3)},Vua=function(a,b){g.Yr("yt-remote-session-browser-channel",a);
g.Yr("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.cb(c,d)||c.push(d);Qua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.gb(a,o6());Qua(a)},Wua=function(){if(!r6){var a=g.Wn();
a&&(r6=new g.Fn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Xua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Yua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Zua(a.shift(),function(){s6(a)}):t6()},$ua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Zua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Yua();
a&&a(!1,"No cast extension found")},bva=function(){if(ava){var a=2,b=Yua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Zua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},cva=function(){bva();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(a,b,c){g.A.call(this);
this.C=null!=c?(0,g.w)(a,c):a;this.Fd=b;this.B=(0,g.w)(this.xF,this);this.o=!1;this.u=0;this.w=this.Ea=null;this.A=[]},v6=function(a,b,c){g.A.call(this);
this.w=null!=c?(0,g.w)(a,c):a;this.Fd=b;this.u=(0,g.w)(this.yF,this);this.o=[]},w6=function(a){a.Ea=g.Af(a.u,a.Fd);
a.w.apply(null,a.o)},x6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Fua(a)},y6=function(){},z6=function(){},dva=function(){},fva=function(a){return(a=eva(a))?new ActiveXObject(a):new XMLHttpRequest},eva=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},A6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.L1(this);this.u=new g.zf;this.u.setInterval(250)},hva=function(a,b,c){a.yj=1;
a.Sg=$5(b.clone());a.Qi=c;a.C=!0;gva(a,null)},B6=function(a,b,c,d,e){a.yj=1;
a.Sg=$5(b.clone());a.Qi=null;a.C=c;e&&(a.hC=!1);gva(a,d)},gva=function(a,b){a.ik=(0,g.C)();
C6(a);a.Gh=a.Sg.clone();a6(a.Gh,"t",a.F);a.Um=0;a.Oc=a.o.ur(a.o.Jm()?b:null);0<a.ks&&(a.Ip=new v6((0,g.w)(a.fD,a,a.Oc),a.ks));a.A.ia(a.Oc,"readystatechange",a.mO);var c=a.ti?g.y.clone(a.ti):{};a.Qi?(a.qq="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Oc.send(a.Gh,a.qq,a.Qi,c)):(a.qq="GET",a.hC&&!g.Rd&&(c.Connection="close"),a.Oc.send(a.Gh,a.qq,null,c));a.o.bf(1)},kva=function(a,b,c){for(var d=!0;!a.Yh&&a.Um<c.length;){var e=iva(a,c);
if(e==D6){4==b&&(a.hh=4,E6(15),d=!1);break}else if(e==jva){a.hh=4;E6(16);d=!1;break}else F6(a,e)}4==b&&0==c.length&&(a.hh=1,E6(17),d=!1);a.df=a.df&&d;d||(G6(a),H6(a))},iva=function(a,b){var c=a.Um,d=b.indexOf("\n",c);
if(-1==d)return D6;c=Number(b.substring(c,d));if(isNaN(c))return jva;d+=1;if(d+c>b.length)return D6;var e=b.substr(d,c);a.Um=d+c;return e},mva=function(a,b){a.ik=(0,g.C)();
C6(a);var c=b?window.location.hostname:"";a.Gh=a.Sg.clone();Z5(a.Gh,"DOMAIN",c);Z5(a.Gh,"t",a.F);try{a.jf=new ActiveXObject("htmlfile")}catch(n){G6(a);a.hh=7;E6(22);H6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in I6)k=I6[l];else if(l in lva)k=I6[l]=lva[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
I6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Dc(g.Eb("b/12014412"),d+"</body></html>");a.jf.open();a.jf.write(g.xc(c));a.jf.close();a.jf.parentWindow.m=(0,g.w)(a.HN,a);a.jf.parentWindow.d=(0,g.w)(a.oB,a,!0);a.jf.parentWindow.rpcClose=(0,g.w)(a.oB,a,!1);c=a.jf.createElement("DIV");a.jf.parentWindow.document.body.appendChild(c);d=g.cc(a.Gh.toString());d=g.Mc(g.ac(d));d=g.Dc(g.Eb("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Ec(c,d);a.o.bf(1)},C6=function(a){a.gv=(0,g.C)()+a.B;
nva(a,a.B)},nva=function(a,b){if(null!=a.Ak)throw Error("WatchDog timer not null");
a.Ak=J6((0,g.w)(a.PN,a),b)},K6=function(a){a.Ak&&(g.v.clearTimeout(a.Ak),a.Ak=null)},H6=function(a){a.o.Mx()||a.Yh||a.o.xp(a)},G6=function(a){K6(a);
g.oe(a.Ip);a.Ip=null;a.u.stop();g.Dpa(a.A);if(a.Oc){var b=a.Oc;a.Oc=null;b.abort();b.dispose()}a.jf&&(a.jf=null)},F6=function(a,b){try{a.o.hB(a,b),a.o.bf(4)}catch(c){}},pva=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;ova(a,b,function(k){k?c(!0):g.v.setTimeout(function(){pva(a,b,c,d,f)},f)})}},ova=function(a,b,c){var d=new Image;
d.onload=function(){try{L6(d),c(!0)}catch(e){}};
d.onerror=function(){try{L6(d),c(!1)}catch(e){}};
d.onabort=function(){try{L6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{L6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Eua(d,a)},L6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},qva=function(a){this.o=a;
this.u=new y6},rva=function(a){var b=M6(a.o,a.Kk,"/mail/images/cleardot.gif");
$5(b);pva(b.toString(),5E3,(0,g.w)(a.sE,a),3,2E3);a.bf(1)},O6=function(a){var b=a.o.H;
if(null!=b)E6(5),b?(E6(11),N6(a.o,a,!1)):(E6(12),N6(a.o,a,!0));else if(a.Zd=new A6(a,void 0,void 0,void 0),a.Zd.ti=a.gs,b=a.o,b=M6(b,b.Jm()?a.rl:null,a.hs),E6(5),!g.Pd||g.td(10))a6(b,"TYPE","xmlhttp"),B6(a.Zd,b,!1,a.rl,!1);else{a6(b,"TYPE","html");var c=a.Zd;a=!!a.rl;c.yj=3;c.Sg=$5(b.clone());mva(c,a)}},P6=function(a){g.Oe.call(this);
this.headers=new g.tm;this.R=a||null;this.w=!1;this.V=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.aa=this.G=this.T=!1;this.F=0;this.J=null;this.ea="";this.M=this.Z=!1},sva=function(a){return g.Pd&&g.sd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},tva=function(a){return"content-type"==a.toLowerCase()},vva=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;uva(a);Q6(a)},uva=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},xva=function(a){if(a.w&&"undefined"!=typeof g.Q1)if(a.V[1]&&4==R6(a)&&2==a.getStatus())S6(a,"Local request error detected and ignored");
else if(a.G&&4==R6(a))g.Af(a.dB,0,a);else if(a.dispatchEvent("readystatechange"),4==R6(a)){S6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Wc(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!wva.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<R6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";uva(a)}}finally{Q6(a)}}},Q6=function(a,b){if(a.o){yva(a);
var c=a.o,d=a.V[0]?g.Ka:null;a.o=null;a.V=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},yva=function(a){a.o&&a.M&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},R6=function(a){return a.o?a.o.readyState:0},T6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},S6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},U6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new y6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},zva=function(a,b){this.o=a;
this.map=b;this.context=null},Ava=function(a){g.qe.call(this,"statevent",a)},Bva=function(a,b){g.qe.call(this,"timingevent",a);
this.size=b},Cva=function(a){g.qe.call(this,"serverreachability",a)},Fva=function(a){Dva(a);
if(3==a.o){var b=a.hm++,c=a.Zn.clone();Z5(c,"SID",a.w);Z5(c,"RID",b);Z5(c,"TYPE","terminate");V6(a,c);b=new A6(a,a.w,b,void 0);b.yj=2;b.Sg=$5(c.clone());Eua(new Image,b.Sg.toString());b.ik=(0,g.C)();C6(b)}Eva(a)},Gva=function(a){a.RE(1,0);
a.Zn=M6(a,null,a.ds);W6(a)},Dva=function(a){a.Wg&&(a.Wg.abort(),a.Wg=null);
a.sc&&(a.sc.cancel(),a.sc=null);a.Vf&&(g.v.clearTimeout(a.Vf),a.Vf=null);X6(a);a.Rd&&(a.Rd.cancel(),a.Rd=null);a.bh&&(g.v.clearTimeout(a.bh),a.bh=null)},Hva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new zva(a.cK++,b));2!=a.o&&3!=a.o||W6(a)},W6=function(a){a.Rd||a.bh||(a.bh=J6((0,g.w)(a.nB,a),0),a.rj=0)},Jva=function(a,b){if(1==a.o){if(!b){a.hm=Math.floor(1E5*Math.random());
var c=a.hm++,d=new A6(a,"",c,void 0);d.ti=null;var e=Y6(a),f=a.Zn.clone();Z5(f,"RID",c);Z5(f,"CVER","1");V6(a,f);hva(d,f,e);a.Rd=d;a.o=2}}else 3==a.o&&(b?Iva(a,b):0==a.u.length||a.Rd||Iva(a))},Iva=function(a,b){if(b)if(6<a.Zh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.hm-1;var d=Y6(a)}else c=b.G,d=b.Qi;else c=a.hm++,d=Y6(a);var e=a.Zn.clone();Z5(e,"SID",a.w);Z5(e,"RID",c);Z5(e,"AID",a.Lj);V6(a,e);c=new A6(a,a.w,c,a.rj+1);c.ti=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Rd=c;hva(c,e,d)},V6=function(a,b){if(a.Bd){var c=a.Bd.jx();
c&&g.y.forEach(c,function(d,e){Z5(b,e,d)})}},Y6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Zh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Zh?e:f-d;try{g.y.forEach(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Kva=function(a){a.sc||a.Vf||(a.F=1,a.Vf=J6((0,g.w)(a.mB,a),0),a.hj=0)},Z6=function(a){if(a.sc||a.Vf||3<=a.hj)return!1;
a.F++;a.Vf=J6((0,g.w)(a.mB,a),Lva(a,a.hj));a.hj++;return!0},N6=function(a,b,c){a.nq=c;
a.vf=b.lg;a.C||Gva(a)},X6=function(a){null!=a.hi&&(g.v.clearTimeout(a.hi),a.hi=null)},Lva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},$6=function(a,b){if(2==b||9==b){var c=null;
a.Bd&&(c=null);var d=(0,g.w)(a.ZO,a);c||(c=new g.xm("//www.google.com/images/cleardot.gif"),$5(c));ova(c.toString(),1E4,d)}else E6(2);Mva(a,b)},Mva=function(a,b){a.o=0;
a.Bd&&a.Bd.zw(b);Eva(a);Dva(a)},Eva=function(a){a.o=0;
a.vf=-1;if(a.Bd)if(0==a.A.length&&0==a.u.length)a.Bd.kr();else{g.kb(a.A);var b=g.kb(a.u);a.A.length=0;a.u.length=0;a.Bd.kr(b)}},M6=function(a,b,c){var d=g.Fm(c);
if(""!=d.o)b&&g.zm(d,b+"."+d.o),g.Am(d,d.A);else{var e=window.location;d=Gua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Zk&&g.y.forEach(a.Zk,function(f,k){Z5(d,k,f)});
Z5(d,"VER",a.Zh);V6(a,d);return d},J6=function(a,b){if(!g.Pa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},E6=function(a){a7.dispatchEvent(new Ava(a7,a))},Nva=function(){},Ova=function(){this.o=[];
this.u=[]},Pva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.A.call(this);
this.o=new g.H(this.yN,0,this);g.B(this,this.o);this.Fd=5E3;this.u=0;if(g.Pa(a))b&&(a=(0,g.w)(a,b));else if(a&&g.Pa(a.handleEvent))a=(0,g.w)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.En;this.u=new b7(this.BO,this);this.o=null;this.wb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.M=c||!1},Qva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.nq,sessionId:a.o.w,arrayId:a.o.Lj}},Rva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Jva(a.o),Fva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Sva=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.Wc(4,a))||"";b&&(this.port=":"+b);this.domain=g.Xc(a)||"";a=g.oc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Wb(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.gd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ta(a.A,d,!0),onError:g.Ta(a.w,e),Xd:g.Ta(a.B,e)};c&&(a.vb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.bq(b,a)},Wva=function(){var a=Tva;
Uva();h7.push(a);Vva(h7)},i7=function(a,b){Uva();
var c=h7,d=Xva(a,String(b));g.db(c)?Yva(d):(Vva(c),(0,g.x)(c,function(e){e(d)}))},Uva=function(){h7||(h7=g.Ja("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},Yva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Vva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.x)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Xva=function(a,b){var c=((0,g.C)()-Zva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.P.call(this);
this.F=a;this.o=[]},$va=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},awa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ce)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=$va(a,b[d])||c;return c},bwa=function(a,b){var c=a.o.length;
a.o=(0,g.ce)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.P.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Ea=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},cwa=function(a){if(a.o.length){var b=(0,g.ic)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.w)(a.IF,a),(0,g.w)(a.HF,a))}},o7=function(a){var b=Mua(Sua());
b=(0,g.ce)(b,function(c){return!c.uuid});
return awa(a,b)},q7=function(a,b){Uua((0,g.ic)(a.o,Kua));
b&&Tua()},s7=function(a,b){g.P.call(this);
this.C=b;var c=g.Zr("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.cb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.sk(this.o))},dwa=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.w)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.w)(function(){c(!1)},a))},t7=function(a,b){a:if(g.y.Sc(b)!=g.y.Sc(a.o))var c=!1;
else{c=g.y.Gb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.sk(a.o)),a.o=b,a.P("screenChange"));ewa(a)},u7=function(a){isNaN(a.w)||g.uo(a.w);
a.w=g.so((0,g.w)(a.xu,a),0<a.A&&a.A<(0,g.C)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},fwa=function(a){var b={};
(0,g.x)(a.C(),function(c){c.token?b[c.token]=c.id:this.Tb("Requesting availability of screen w/o lounge token.")});
return b},ewa=function(a){a=g.y.Gb(g.y.filter(a.o,function(b){return b}));
g.tb(a);a.length?g.Yr("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};gwa(this)},iwa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);dwa(a.u,l,function(m){e(m?l:null)})}else c?hwa(a,c,(0,g.w)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));dwa(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},jwa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},hwa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={vb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.bq(f7(a.C,"/pairing/get_lounge_token_batch"),e)},kwa=function(a){a.o=a.w.ne();
for(var b=g.y.GC(a.B),c=0,d=a.o.length;c<d;++c){var e=a.o[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},gwa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.w)(a.RF,a));kwa(a);a.A=Mua(g.Zr("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.w)(a.ne,a,!0));a.u.subscribe("screenChange",(0,g.w)(function(){this.P("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Yr("yt-remote-automatic-screen-cache",(0,g.ic)(a.A,Kua)));x7(a);a.B[b.uuid]=b.id;g.Yr("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.Zr("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.P.call(this);
this.V=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.V,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.w)(this.JP,this);this.B=(0,g.w)(this.XN,this);this.A=g.so((0,g.w)(function(){lwa(this,null)},this),12E4)},mwa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.sk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ka,(0,g.w)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.sk(b))},lwa=function(a,b){g.uo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.w)(a.zp,a),d=(0,g.w)(a.qe,a);a.Fx(b,c,d,5)}}else a.qe(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.R=c;this.B=null;this.F=g.Ka;this.C=NaN;this.M=(0,g.w)(this.MP,this);this.o=g.Ka},nwa=function(a){a.o=a.H.mD(a.J,a.u.label,a.u.friendlyName,(0,g.w)(function(b){this.o=g.Ka;
this.zp(b)},a),(0,g.w)(function(b){this.o=g.Ka;
this.qe(b)},a))},owa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Wua()&&(b.env_useStageMdx=1);return g.ed(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.so((0,g.w)(this.Mj,this,null),150)},D7=function(a,b,c,d){g.P.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.w)(this.GM,this)},pwa=function(a,b){return b?g.$a(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Tva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.oe(a.o),(a.o=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.u):a.P("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.w)(a.lB,a,b)),b.w?a.P("yt-remote-cast2-session-change",b.w):c&&a.o.Mj(null)):a.P("yt-remote-cast2-session-change",null))},qwa=function(a){var b=a.u.lD(),c=a.o&&a.o.u;
a=(0,g.ic)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=pwa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},wwa=function(a,b,c,d,e,f,k){rwa()?swa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?twa(a,c):(window.__onGCastApiAvailable=function(l,m){l?twa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),uwa(),c(!1))},d?g.Eo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?cva():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(bva(),s6(vwa.map($ua))))):H7("Cannot initialize because not running Chrome")},uwa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);xwa(!1);g.Ao(M7);M7.length=0},N7=function(){return!!g.Zr("yt-remote-cast-installed")},ywa=function(){var a=g.Zr("yt-remote-cast-receiver");
return a?a.friendlyName:null},zwa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},Awa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.zo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},rwa=function(){var a=0<=g.oc.search(/ (CrMo|Chrome|CriOS)\//);
return g.tw||a},Bwa=function(a,b){L7().init(a,b)},swa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Yr("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.Yr("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.Yr("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.Ja("yt.mdx.remote.cloudview.instance_")},twa=function(a,b){K7(!0);
I7(!1);Bwa(a,function(c){c?(xwa(!0),g.Bo("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),uwa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.Yr("yt-remote-cast-installed",a)},O7=function(){return!!g.Ja("yt.mdx.remote.cloudview.apiReady_")},xwa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.J=!1;this.H=this.G=this.u=this.B=0;this.A=NaN;this.w=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.J=!1;a.hasNext=!1;a.F=0;a.C=(0,g.C)();a.B=0;a.u=0;a.G=0;a.H=0;a.A=NaN;a.w=!1},T7=function(a){return a.Ya()?((0,g.C)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.C)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.y.Rm(a.o);b.hasPrevious=a.J;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.B;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.A;return b},Z7=function(a,b){g.P.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Ova;this.w=this.u=null;this.H=(0,g.w)(this.JK,this);this.F=(0,g.w)(this.jm,this);this.G=(0,g.w)(this.IK,this);this.J=(0,g.w)(this.UK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.kv,this),Cwa(this))):c=3;0!=c&&(b?this.kv(c):g.so((0,g.w)(function(){this.kv(c)},this),0));
var d=Awa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},Cwa=function(a){(0,g.x)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Ta(this.DM,b),this))},a)},Dwa=function(a){(0,g.x)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){50>a.B.Sc()&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){Dwa(a);
a.A.setPlayerContextData(X7(b));Cwa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.jm(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.jm(a.w.media[0]))},Ewa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.w)(function(d){this.Tb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Tb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.P.call(this);
this.B=NaN;this.M=!1;this.G=this.F=this.H=this.J=NaN;this.V=[];this.A=this.C=this.w=this.Ra=this.o=null;this.T=a;this.V.push(g.cp(window,"beforeunload",(0,g.w)(this.AF,this)));this.u=[];this.Ra=new R7;this.R=b.id;this.o=Fwa(this,c);this.o.subscribe("handlerOpened",this.NK,this);this.o.subscribe("handlerClosed",this.KK,this);this.o.subscribe("handlerError",this.LK,this);this.o.subscribe("handlerMessage",this.MK,this);Sva(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ra.videoId;
g.$r()&&g.Yr("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Fwa=function(a,b){return new c7(f7(a.T,"/bc"),b)},h8=function(a,b){a.P("proxyStateChange",b)},Gwa=function(a){a.B=g.so((0,g.w)(function(){g8("Connecting timeout");
this.oj(1)},a),2E4)},i8=function(a){g.uo(a.B);
a.B=NaN},j8=function(a){g.uo(a.J);
a.J=NaN},Hwa=function(a){k8(a);
a.H=g.so((0,g.w)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.uo(a.H);
a.H=NaN},Jwa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Dx()&&a.Ra.reset(),h8(a,1),l8(a,"getNowPlaying"),Iwa(a)):a.oj(1)},Kwa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ra.videoId&&(g.y.isEmpty(b.params)?a.Ra.o=null:a.Ra.o=b.params,a.P("remotePlayerChange"))},Lwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ra.listId=b.params.listId||a.Ra.listId;W7(a.Ra,c,d);a.P("remoteQueueChange")},Nwa=function(a,b){b.params=b.params||{};
Lwa(a,b);Mwa(a,b);a.P("autoplayDismissed")},Mwa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Ra,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ra.playerState&&(c=-1E3);a.Ra.playerState=c;c=Number(b.params.loadedTime);a.Ra.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Ra.G=isNaN(c)?0:c;c=a.Ra;var d=Number(b.params.liveIngestionTime);c.A=d;c.w=isNaN(d)?!1:!0;c=a.Ra;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Ra.playerState?Hwa(a):k8(a);a.P("remotePlayerChange")},Owa=function(a,b){if(-1E3!=
a.Ra.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ra.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Ra,isNaN(c)?0:c);a.P("remotePlayerChange")}},Pwa=function(a,b){var c="true"==b.params.muted;
a.Ra.volume=parseInt(b.params.volume,10);a.Ra.muted=c;a.P("remotePlayerChange")},Qwa=function(a,b){a.C=b.params.videoId;
a.P("nowAutoplaying",parseInt(b.params.timeout,10))},Rwa=function(a,b){var c="true"==b.params.hasNext;
a.Ra.J="true"==b.params.hasPrevious;a.Ra.hasNext=c;a.P("previousNextChange")},Iwa=function(a){g.uo(a.G);
a.G=g.so((0,g.w)(a.oj,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.sk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.Ed=a;this.u=[];this.u.push(this.Ed.$_s("screenChange",(0,g.w)(this.HP,this)));this.u.push(this.Ed.$_s("onlineScreenChange",(0,g.w)(this.gM,this)))},Wwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;Oua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Wua()&&(n8.o="/api/loungedev"));o8||(o8=g.Ja("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));Swa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);wwa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.Ja("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.sk(b)),s8.push(g.zo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.zo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.zo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.zo("yt-remote-cast2-session-change",Twa)),s8.push(g.zo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),zwa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.io("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.sk(a)),Uwa(a),c.start(),q8()||Vwa())},Ywa=function(){var a=Xwa();
N7()&&g.Zr("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Xwa=function(){var a=p8().Ed.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Nua(a)},y8=function(){var a=Zwa();
!a&&N7()&&ywa()&&(a={key:"cast-selector-receiver",name:ywa()});return a},Zwa=function(){var a=Xwa(),b=w8();
b||(b=u8());return g.$a(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().ne();return k6(b,a)},Twa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.Ja("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.Ja("yt.mdx.remote.currentScreenId_")},$wa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},axa=function(){return g.Ja("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.Ja("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||$wa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.x)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.$r();
if(!a)return null;var b=p8().ne();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{$wa(a.id);var c=new f8(n8,a,v8());c.connect(b,axa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Vwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),zwa(),r8("Skipping connecting because no session screen found."))},Swa=function(){var a=v8();
if(g.y.isEmpty(a)){a=o6();var b=g.Zr("yt-remote-session-name")||"",c=g.Zr("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.Ja("yt.mdx.remote.channelParams_")||{}},Uwa=function(a){a?(g.Yr("yt-remote-session-app",a.app),g.Yr("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.A.call(this);
this.B=a;this.u=b;this.w=new g.O(this);g.B(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.EL);this.w.L(b,"captionschanged",this.HK);this.w.L(b,"captionssettingschanged",this.xC);this.w.L(b,"videoplayerreset",this.Ap);this.w.L(b,"mdxautoplaycancel",this.rE);this.R=this.w.L(b,"onVolumeChange",this.MA);this.G=!1;this.o=c;c.ga();c.subscribe("proxyStateChange",this.gB,this);c.subscribe("remotePlayerChange",this.sm,this);c.subscribe("remoteQueueChange",this.Ap,this);c.subscribe("autoplayUpNext",
this.xA,this);c.subscribe("previousNextChange",this.cB,this);c.subscribe("nowAutoplaying",this.XA,this);c.subscribe("autoplayDismissed",this.wA,this);this.suggestion=null;this.H=new g.cC(64);this.A=new g.H(this.vC,500,this);g.B(this,this.A);this.C=new g.H(this.wC,1E3,this);g.B(this,this.C);this.M=new u6(this.iP,0,this);g.B(this,this.M);this.F={};this.V=new g.H(this.XC,1E3,this);g.B(this,this.V);this.J=new v6(this.rI,1E3,this);g.B(this,this.J);this.T=g.Ka;this.xC();this.Ap();this.sm()},H8=function(a,
b){var c=a.B,d=a.u.getVideoData().lengthSeconds;
c.V=b||0;c.player.P("progresssync",b,d)},bxa=function(a){H8(a,0);
a.A.stop();I8(a,new g.cC(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.y.extend(c,b));a.o.mC(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.xf,Cua(c));I8(a,new g.cC(1))},cxa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{GT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.iC(c,b)){var d=g.V(b,2);d!=g.V(a.H,2)&&g.gS(a.u.app,d);a.H=b;dxa(a.B,c,b)}},M8=function(){g.Q.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",O:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"You're signed out"},{D:"div",I:"ytp-mdx-popup-description",W:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",Y:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancel"},{D:"button",Y:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],W:"Confirm"}]}]}]});this.u=new g.fL(this,250);g.B(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.Q.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.hL()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.fL(this,250);g.B(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);exa(this,g.eK(a))},exa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.LL("Error on $RECEIVER_NAME",c):b.Ya()||g.V(b,4)?g.LL("Playing on $RECEIVER_NAME",c):g.LL("Connected to $RECEIVER_NAME",c);a.ka("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.GN.call(this,"Play on",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.KK.call(this,a);
this.u={key:i6(),name:"This computer"};this.B=null;this.A=[];this.R=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.cC(64);this.V=0;this.H=-1;this.C=null;if(!g.oy(this.player.N())){a=this.player;var b=g.xB(a);b&&(b=b.Xl())&&(b=new O8(a,b),g.B(this,b));b=new N8(a);g.B(this,b);g.xK(a,b.element,4);this.C=new M8;g.B(this,this.C);g.xK(a,this.C.element,4);this.M=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},dxa=function(a,b,c){a.F=
c;
a.player.P("presentingplayerstatechange",new g.nC(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.M||!a.C);if(c?0:g.yy(a.player.N())||"WEB_EMBEDDED_PLAYER"==a.player.N().deviceParams.c)g.eK(a.player).Ya()?a.player.pauseVideo():(a.G=(0,g.w)(a.bO,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.Zb(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=
c.videoId;if(!d&&!e||(2==a.player.getAppState()||1==a.player.getAppState())&&g.R(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.va(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.xf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=Cua(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+
g.sk(b));"cast-selector-receiver"==b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().ne(),(c=k6(c,b.key))&&A8(c,1))}},lva={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},I6={"'":"\\'"},fxa={},Jua={kQ:"atp",QS:"ska",FS:"que",ZR:"mus",PS:"sus",lR:"dsp",MS:"seq"};
d6.prototype.fi=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
d6.prototype.rb=function(a){return a?this.id==a.id:!1};
var r6,n6="",ava=Xua("loadCastFramework")||Xua("loadCastApplicationFramework"),vwa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Va(u6,g.A);g.h=u6.prototype;g.h.wF=function(a){this.A=arguments;this.o=!1;this.Ea?this.w=(0,g.C)()+this.Fd:this.Ea=g.Af(this.B,this.Fd)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.X=function(){this.stop();u6.Fb.X.call(this)};
g.h.xF=function(){this.w?(this.Ea=g.Af(this.B,this.w-(0,g.C)()),this.w=null):(this.Ea=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.Va(v6,g.A);g.h=v6.prototype;g.h.xj=!1;g.h.ql=0;g.h.Ea=null;g.h.Lx=function(a){this.o=arguments;this.Ea||this.ql?this.xj=!0:w6(this)};
g.h.stop=function(){this.Ea&&(g.v.clearTimeout(this.Ea),this.Ea=null,this.xj=!1,this.o=[])};
g.h.pause=function(){this.ql++};
g.h.resume=function(){this.ql--;this.ql||!this.xj||this.Ea||(this.xj=!1,w6(this))};
g.h.X=function(){v6.Fb.X.call(this);this.stop()};
g.h.yF=function(){this.Ea=null;this.xj&&!this.ql&&(this.xj=!1,w6(this))};y6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};z6.prototype.o=null;z6.prototype.getOptions=function(){var a;(a=this.o)||(a={},eva(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Va(dva,z6);S8=new dva;g.h=A6.prototype;g.h.ti=null;g.h.df=!1;g.h.Ak=null;g.h.gv=null;g.h.ik=null;g.h.yj=null;g.h.Sg=null;g.h.Gh=null;g.h.Qi=null;g.h.Oc=null;g.h.Um=0;g.h.jf=null;g.h.qq=null;g.h.hh=null;g.h.sl=-1;g.h.hC=!0;g.h.Yh=!1;g.h.ks=0;g.h.Ip=null;var jva={},D6={};g.h=A6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.mO=function(a){a=a.target;var b=this.Ip;b&&3==R6(a)?b.Lx():this.fD(a)};
g.h.fD=function(a){try{if(a==this.Oc)a:{var b=R6(this.Oc),c=this.Oc.C,d=this.Oc.getStatus();if(g.Pd&&!g.td(10)||g.Rd&&!g.sd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.fh&&!T6(this.Oc))break a;this.Yh||4!=b||7==c||(8==c||0>=d?this.o.bf(3):this.o.bf(2));K6(this);var e=this.Oc.getStatus();this.sl=e;var f=T6(this.Oc);(this.df=200==e)?(4==b&&G6(this),this.C?(kva(this,b,f),g.fh&&this.df&&3==b&&(this.A.ia(this.u,"tick",this.fO),this.u.start())):F6(this,f),this.df&&!this.Yh&&(4==b?this.o.xp(this):(this.df=
!1,C6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.hh=3,E6(13)):(this.hh=0,E6(14)),G6(this),H6(this))}}catch(k){this.Oc&&T6(this.Oc)}finally{}};
g.h.fO=function(){var a=R6(this.Oc),b=T6(this.Oc);this.Um<b.length&&(K6(this),kva(this,a,b),this.df&&4!=a&&C6(this))};
g.h.HN=function(a){J6((0,g.w)(this.GN,this,a),0)};
g.h.GN=function(a){this.Yh||(K6(this),F6(this,a),C6(this))};
g.h.oB=function(a){J6((0,g.w)(this.FN,this,a),0)};
g.h.FN=function(a){this.Yh||(G6(this),this.df=a,this.o.xp(this),this.o.bf(4))};
g.h.cancel=function(){this.Yh=!0;G6(this)};
g.h.PN=function(){this.Ak=null;var a=(0,g.C)();0<=a-this.gv?(2!=this.yj&&this.o.bf(3),G6(this),this.hh=2,E6(18),H6(this)):nva(this,this.gv-a)};
g.h.getLastError=function(){return this.hh};g.h=qva.prototype;g.h.gs=null;g.h.Zd=null;g.h.Jp=!1;g.h.Nx=null;g.h.Wn=null;g.h.Os=null;g.h.hs=null;g.h.Ce=null;g.h.lg=-1;g.h.rl=null;g.h.Kk=null;g.h.connect=function(a){this.hs=a;a=M6(this.o,null,this.hs);E6(3);this.Nx=(0,g.C)();var b=this.o.G;null!=b?(this.rl=b[0],(this.Kk=b[1])?(this.Ce=1,rva(this)):(this.Ce=2,O6(this))):(a6(a,"MODE","init"),this.Zd=new A6(this,void 0,void 0,void 0),this.Zd.ti=this.gs,B6(this.Zd,a,!1,null,!0),this.Ce=0)};
g.h.sE=function(a){if(a)this.Ce=2,O6(this);else{E6(4);var b=this.o;b.vf=b.Wg.lg;$6(b,9)}a&&this.bf(2)};
g.h.ur=function(a){return this.o.ur(a)};
g.h.abort=function(){this.Zd&&(this.Zd.cancel(),this.Zd=null);this.lg=-1};
g.h.Mx=function(){return!1};
g.h.hB=function(a,b){this.lg=a.sl;if(0==this.Ce)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.vf=this.lg;$6(c,2);return}this.rl=c[0];this.Kk=c[1]}else c=this.o,c.vf=this.lg,$6(c,2);else if(2==this.Ce)if(this.Jp)E6(7),this.Os=(0,g.C)();else if("11111"==b){if(E6(6),this.Jp=!0,this.Wn=(0,g.C)(),c=this.Wn-this.Nx,!g.Pd||g.td(10)||500>c)this.lg=200,this.Zd.cancel(),E6(12),N6(this.o,this,!0)}else E6(8),this.Wn=this.Os=(0,g.C)(),this.Jp=!1};
g.h.xp=function(){this.lg=this.Zd.sl;if(this.Zd.df)0==this.Ce?this.Kk?(this.Ce=1,rva(this)):(this.Ce=2,O6(this)):2==this.Ce&&((!g.Pd||g.td(10)?!this.Jp:200>this.Os-this.Wn)?(E6(11),N6(this.o,this,!1)):(E6(12),N6(this.o,this,!0)));else{0==this.Ce?E6(9):2==this.Ce&&E6(10);var a=this.o;this.Zd.getLastError();a.vf=this.lg;$6(a,2)}};
g.h.Jm=function(){return this.o.Jm()};
g.h.isActive=function(){return this.o.isActive()};
g.h.bf=function(a){this.o.bf(a)};g.Va(P6,g.Oe);var wva=/^https?$/i,gxa=["POST","PUT"];g.h=P6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.T=!1;this.w=!0;this.o=this.R?fva(this.R):fva(S8);this.V=this.R?this.R.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.w)(this.dB,this);try{b6(S6(this,"Opening Xhr")),this.aa=!0,this.o.open(b,String(a),!0),this.aa=!1}catch(f){b6(S6(this,"Error opening Xhr: "+f.message));vva(this,f);return}a=
c||"";var e=this.headers.clone();d&&g.wm(d,function(f,k){e.set(k,f)});
d=g.$a(e.Gb(),tva);c=g.v.FormData&&a instanceof g.v.FormData;!g.cb(gxa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.Z&&(this.o.withCredentials=this.Z);try{yva(this),0<this.F&&(this.M=sva(this.o),b6(S6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.M)),this.M?(this.o.timeout=this.F,this.o.ontimeout=(0,g.w)(this.Ox,this)):this.J=g.Af(this.Ox,this.F,this)),b6(S6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(S6(this,"Send error: "+f.message)),vva(this,f)}};
g.h.Ox=function(){"undefined"!=typeof g.Q1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,S6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(S6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Q6(this))};
g.h.X=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),Q6(this,!0));P6.Fb.X.call(this)};
g.h.dB=function(){this.ga()||(this.aa||this.G||this.B?xva(this):this.FM())};
g.h.FM=function(){xva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<R6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=U6.prototype;g.h.Zk=null;g.h.Rd=null;g.h.sc=null;g.h.ds=null;g.h.Zn=null;g.h.lw=null;g.h.oo=null;g.h.hm=0;g.h.cK=0;g.h.Bd=null;g.h.bh=null;g.h.Vf=null;g.h.hi=null;g.h.Wg=null;g.h.nq=null;g.h.Lj=-1;g.h.vy=-1;g.h.vf=-1;g.h.rj=0;g.h.hj=0;g.h.Zh=8;var a7=new g.Oe;g.Va(Ava,g.qe);g.Va(Bva,g.qe);g.Va(Cva,g.qe);g.h=U6.prototype;g.h.connect=function(a,b,c,d,e){E6(0);this.ds=b;this.Zk=c||{};d&&void 0!==e&&(this.Zk.OSID=d,this.Zk.OAID=e);this.C?(J6((0,g.w)(this.Gw,this,a),100),Gva(this)):this.Gw(a)};
g.h.Gw=function(a){this.Wg=new qva(this);this.Wg.gs=null;this.Wg.u=this.B;this.Wg.connect(a)};
g.h.Mx=function(){return 0==this.o};
g.h.nB=function(a){this.bh=null;Jva(this,a)};
g.h.mB=function(){this.Vf=null;this.sc=new A6(this,this.w,"rpc",this.F);this.sc.ti=null;this.sc.ks=0;var a=this.lw.clone();Z5(a,"RID","rpc");Z5(a,"SID",this.w);Z5(a,"CI",this.nq?"0":"1");Z5(a,"AID",this.Lj);V6(this,a);if(!g.Pd||g.td(10))Z5(a,"TYPE","xmlhttp"),B6(this.sc,a,!0,this.oo,!1);else{Z5(a,"TYPE","html");var b=this.sc,c=!!this.oo;b.yj=3;b.Sg=$5(a.clone());mva(b,c)}};
g.h.hB=function(a,b){if(0!=this.o&&(this.sc==a||this.Rd==a))if(this.vf=a.sl,this.Rd==a&&3==this.o)if(7<this.Zh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Vf){if(this.sc)if(this.sc.ik+3E3<this.Rd.ik)X6(this),this.sc.cancel(),this.sc=null;else break a;Z6(this);E6(19)}}else this.vy=c[1],0<this.vy-this.Lj&&37500>c[2]&&this.nq&&0==this.hj&&!this.hi&&(this.hi=J6((0,g.w)(this.DK,this),6E3));else $6(this,11)}else b!=fxa.HQ.o&&$6(this,11);else if(this.sc==
a&&X6(this),!g.Lb(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Lj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.oo=e[2],e=e[3],null!=e?this.Zh=e:this.Zh=6,this.o=3,this.Bd&&this.Bd.Bw(),this.lw=M6(this,this.Jm()?this.oo:null,this.ds),Kva(this)):"stop"==e[0]&&$6(this,7):3==this.o&&("stop"==e[0]?$6(this,7):"noop"!=e[0]&&this.Bd&&this.Bd.Aw(e),this.hj=0)}}};
g.h.DK=function(){null!=this.hi&&(this.hi=null,this.sc.cancel(),this.sc=null,Z6(this),E6(20))};
g.h.xp=function(a){if(this.sc==a){X6(this);this.sc=null;var b=2}else if(this.Rd==a)this.Rd=null,b=1;else return;this.vf=a.sl;if(0!=this.o)if(a.df)1==b?(b=(0,g.C)()-a.ik,a7.dispatchEvent(new Bva(a7,a.Qi?a.Qi.length:0,b,this.rj)),W6(this),this.A.length=0):Kva(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.vf)){if(d=1==b)this.Rd||this.bh||1==this.o||2<=this.rj?d=!1:(this.bh=J6((0,g.w)(this.nB,this,a),Lva(this,this.rj)),this.rj++,d=!0);d=!(d||2==b&&Z6(this))}if(d)switch(c){case 1:$6(this,
5);break;case 4:$6(this,10);break;case 3:$6(this,6);break;case 7:$6(this,12);break;default:$6(this,2)}}};
g.h.RE=function(a){if(!g.cb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.ZO=function(a){a?E6(2):(E6(1),Mva(this,8))};
g.h.ur=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new P6;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Bd&&this.Bd.isActive(this)};
g.h.bf=function(a){a7.dispatchEvent(new Cva(a7,a))};
g.h.Jm=function(){return!(!g.Pd||g.td(10))};
g.h=Nva.prototype;g.h.Bw=function(){};
g.h.Aw=function(){};
g.h.zw=function(){};
g.h.kr=function(){};
g.h.jx=function(){return{}};
g.h.isActive=function(){return!0};g.h=Ova.prototype;g.h.Sc=function(){return this.o.length+this.u.length};
g.h.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.cb(this.o,a)||g.cb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Ipa)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.h.uc=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Va(b7,g.A);g.h=b7.prototype;g.h.yN=function(){this.Fd=Math.min(3E5,2*this.Fd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.fn(this.o,a);this.u=(0,g.C)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.Va(c7,Nva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.xh=function(a){return this.w.vi(a)};
g.h.P=function(a,b){return this.w.P.apply(this.w,arguments)};
g.h.dispose=function(){this.wb||(this.wb=!0,g.oe(this.w),Rva(this),g.oe(this.u),this.u=null)};
g.h.ga=function(){return this.wb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new U6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.Bd=null);d.Bd=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.Lj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.y.extend(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Hva(this.o,c)};
g.h.Bw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Hva(this.o,a[b])}this.P("handlerOpened")};
g.h.zw=function(a){var b=2==a&&401==this.o.vf;4==a||b||this.u.start();this.P("handlerError",a)};
g.h.kr=function(a){if(!this.u.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.jx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.y.extend(a,this.B);return a};
g.h.Aw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Fva(this.o)):this.P("handlerMessage",new Pva(a[0],a[1]))};
g.h.BO=function(){this.u.isActive();var a=this.o,b=0;a.sc&&b++;a.Rd&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Zva=(0,g.C)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Va(m7,g.P);m7.prototype.ne=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.P);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.kD()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.uo(this.Ea),this.Ea=NaN)};
g.h.X=function(){this.stop();g.P.prototype.X.call(this)};
g.h.kD=function(){this.Ea=NaN;this.o=g.bq(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.w)(this.FP,this),onError:(0,g.w)(this.EP,this),Xd:(0,g.w)(this.GP,this)})};
g.h.FP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.P("pairingComplete",new e6(c))};
g.h.EP=function(a){this.o=null;a.status&&404==a.status?this.u>=hxa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=hxa[this.u],this.Ea=g.so((0,g.w)(this.kD,this),a),this.u++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.GP=function(){this.o=null;this.P("pairingFailed",Error("Server not responding"))};
var hxa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Va(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.P("screenChange");!g.Zr("yt-remote-lounge-token-expiration")&&cwa(this);g.uo(this.u);this.u=g.so((0,g.w)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);$va(this,a);q7(this,!1);this.P("screenChange");b(a);a.token||cwa(this)};
g.h.remove=function(a,b){var c=o7(this);bwa(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.lq=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.X=function(){g.uo(this.u);p7.Fb.X.call(this)};
g.h.IF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.HF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.P);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.Zr("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.C)()-144E5<a?0:a)?u7(this):(this.A=(0,g.C)()+3E5,g.Yr("yt-remote-fast-check-period",this.A),this.xu())};
g.h.isEmpty=function(){return g.y.isEmpty(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.y.filter(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.X=function(){g.uo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.P.prototype.X.call(this)};
g.h.xu=function(){g.uo(this.w);this.w=NaN;this.u&&this.u.abort();var a=fwa(this);if(g.y.Sc(a)){var b=f7(this.B,"/pairing/get_screen_availability"),c={lounge_token:g.y.Gb(a).join(",")};this.u=g7(this.B,b,c,(0,g.w)(this.dN,this,a),(0,g.w)(this.cN,this))}else t7(this,{}),u7(this)};
g.h.dN=function(a,b){this.u=null;var c=g.y.Gb(fwa(this));if(g.ub(c,g.y.Gb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Tb("Changing Screen set during request."),this.xu()};
g.h.cN=function(a){this.Tb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Tb=function(a){i7("OnlineScreenService",a)};g.Va(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.P("screenChange"),this.u.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.lq=function(a,b,c,d){this.w.contains(a)?this.w.lq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.ne=function(a){return a?this.o:g.jb(this.o,(0,g.ce)(this.A,function(b){return!this.contains(b)},this))};
g.h.lD=function(){return(0,g.ce)(this.ne(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.mD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.w)(function(k){g.oe(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.oe(f);e(k)});
f.start();return(0,g.w)(f.stop,f)};
g.h.IP=function(a,b,c,d){g.bq(f7(this.C,"/pairing/get_screen"),{method:"POST",vb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.w)(function(e,f){var k=new e6(f.screen||{});if(!k.name||jwa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);jwa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.w)(function(e){d(Error("pairing request failed: "+e.status))},this),
Xd:(0,g.w)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.oe(this.w);g.oe(this.u);v7.Fb.X.call(this)};
g.h.RF=function(){kwa(this);this.P("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Va(y7,g.P);g.h=y7.prototype;g.h.zp=function(a){this.w=a;this.P("sessionScreen",this.w)};
g.h.qe=function(a){this.ga()||(a&&z7(this,""+a),this.w=null,this.P("sessionScreen",null))};
g.h.info=function(a){i7(this.V,a)};
g.h.oD=function(){return null};
g.h.Gu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.w)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.w)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.Gu("");y7.Fb.X.call(this)};g.Va(A7,y7);g.h=A7.prototype;g.h.Fu=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);mwa(this)};
g.h.Mj=function(a){this.info("launchWithParams no-op for Cast: "+g.sk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.w)(function(){this.qe()},this),(0,g.w)(function(){this.qe(Error("Failed to stop receiver app."))},this)):this.qe(Error("Stopping cast device witout session."))};
g.h.Gu=g.Ka;g.h.X=function(){this.info("disposeInternal");g.uo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Fb.X.call(this)};
g.h.XN=function(a,b){if(!this.ga())if(b){var c=x6(b);if(g.Qa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.sk(c));switch(d){case "mdxSessionStatus":lwa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Fx=function(a,b,c,d){iwa(this.H,this.u.label,a,this.u.friendlyName,(0,g.w)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.so((0,g.w)(this.Fx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.oD=function(){return this.o};
g.h.JP=function(a){this.ga()||a||(z7(this,"Cast session died."),this.qe())};g.Va(B7,y7);g.h=B7.prototype;g.h.Fu=function(a){this.A=a;this.A.addUpdateListener(this.M)};
g.h.Mj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ka;g.uo(this.C);this.A?this.A.stop((0,g.w)(this.qe,this,null),(0,g.w)(this.qe,this,"Failed to stop DIAL device.")):this.qe()};
g.h.X=function(){this.o();this.o=g.Ka;g.uo(this.C);this.A&&this.A.removeUpdateListener(this.M);this.A=null;B7.Fb.X.call(this)};
g.h.MP=function(a){this.ga()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ka,this.qe())};
g.h.ys=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,owa(this));a(b);nwa(this)}else this.F=(0,g.w)(function(){g.uo(this.C);this.F=g.Ka;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,owa(this));a(c);nwa(this)},this),this.C=g.so((0,g.w)(function(){this.F()},this),100)};
g.h.kG=function(a,b,c){iwa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.w)(function(d){d&&d.token?(this.zp(d),b(new chrome.cast.DialLaunchResponse(!1))):this.ys(b,c)},this),(0,g.w)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.ys(b,c)},this))};g.Va(C7,y7);C7.prototype.stop=function(){this.qe()};
C7.prototype.Fu=g.Ka;C7.prototype.Mj=function(){g.uo(this.o);this.o=NaN;var a=k6(this.H.ne(),this.u.label);a?this.zp(a):this.qe(Error("No such screen"))};
C7.prototype.X=function(){g.uo(this.o);this.o=NaN;C7.Fb.X.call(this)};g.Va(D7,g.P);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.w)(this.KM,this);c=new chrome.cast.ApiConfig(c,(0,g.w)(this.jB,this),f,d,e);c.customDialLaunchCallback=(0,g.w)(this.cL,this);chrome.cast.initialize(c,(0,g.w)(function(){this.ga()||
(chrome.cast.addReceiverActionListener(this.A),Wva(),this.u.subscribe("onlineScreenChange",(0,g.w)(this.nD,this)),this.w=qwa(this),chrome.cast.setCustomReceivers(this.w,g.Ka,(0,g.w)(function(k){this.Tb("Failed to set initial custom receivers: "+g.sk(k))},this)),this.P("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.w)(function(k){this.Tb("Failed to initialize API: "+g.sk(k));
b(!1)},this))};
g.h.JO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.ne(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=pwa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ka,(0,g.w)(function(e){this.Tb("Failed to set initial custom receivers: "+g.sk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.Gu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.KO=function(a){this.ga()?this.Tb("Setting connection data on disposed cast v2"):this.o?this.o.Mj(a):this.Tb("Setting connection data without a session")};
g.h.LP=function(){this.ga()?this.Tb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.w)(this.jB,this),(0,g.w)(this.gN,this))};
g.h.X=function(){this.u.unsubscribe("onlineScreenChange",(0,g.w)(this.nD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Tva,b=g.Ja("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.oe(this.o);D7.Fb.X.call(this)};
g.h.Tb=function(a){i7("Controller",a)};
g.h.lB=function(a,b){this.o==a&&(b||G7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.GM=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.P("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Tb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Tb("Stopping receiver w/o session: "+a.friendlyName)}else this.Tb("onReceiverAction_ called without receiver.")};
g.h.cL=function(a){if(this.ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Tb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Tb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Tb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.w)(b.kG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.w)(b.ys,b))};
g.h.jB=function(a){if(!this.ga()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Tb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.ne(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.oe(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.w)(this.lB,this,this.o)),this.o.Mj(null));this.o.Fu(a)}}};
g.h.KP=function(){return this.o?this.o.oD():null};
g.h.gN=function(a){this.ga()||(this.Tb("Failed to estabilish a session: "+g.sk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.KM=function(a){E7("Receiver availability updated: "+a);if(!this.ga()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.P("yt-remote-cast2-availability-change",F7(this))}};
g.h.nD=function(){this.ga()||(this.w=qwa(this),E7("Updating custom receivers: "+g.sk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ka,(0,g.w)(function(){this.Tb("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.KO;D7.prototype.setConnectedScreenStatus=D7.prototype.JO;D7.prototype.stopSession=D7.prototype.LP;D7.prototype.getCastSession=D7.prototype.KP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];g.h=R7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.J=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.B=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.A=a.liveIngestionTime,this.w=!isNaN(this.A))};
g.h.Ya=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.w?this.G+T7(this):this.G};
g.h.clone=function(){return new R7(X7(this))};g.r(Z7,g.P);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ka,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ka,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.P("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ya()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ka,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.P("remotePlayerChange")}else a8(this,g.Ta(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ka,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.P("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.w)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.w)(function(){this.Tb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.w)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.w)(function(){this.Tb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Ta(this.setVolume,a,b))};
g.h.mC=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.sk(b.style),g.y.extend(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Ta(this.mC,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Ta(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.sk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.jD=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Ta(this.jD,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Ta(this.nextVideo,a,b))};
g.h.Pw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Pw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.P("proxyStateChange",a,this.o)}g.P.prototype.dispose.call(this)};
g.h.X=function(){Dwa(this);this.A=null;this.B.clear();Y7(this,null);g.P.prototype.X.call(this)};
g.h.kv=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.DM=function(a,b){this.P(a,b)};
g.h.JK=function(a){if(!a)this.jm(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.jm=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Ewa(this),this.P("remotePlayerChange")};
g.h.IK=function(a){a?(Ewa(this),this.P("remotePlayerChange")):this.jm(null)};
g.h.UK=function(){var a=Awa();a&&Y7(this,a)};
g.h.Tb=function(a){i7("CP",a)};g.r(f8,g.P);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Ra.listId=c);this.Ra.videoId=d;this.Ra.index=k||0;this.Ra.state=3;U7(this.Ra,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.sk(l));this.o.connect({method:"setPlaylist",
params:g.sk(l)},a,Rua())}else g8("Connecting without params"),this.o.connect({},a,Rua());Gwa(this)};
g.h.dispose=function(){this.ga()||(this.P("beforeDispose"),h8(this,3));g.P.prototype.dispose.call(this)};
g.h.X=function(){i8(this);k8(this);j8(this);g.uo(this.F);this.F=NaN;g.uo(this.G);this.G=NaN;this.w=null;g.dp(this.V);this.V.length=0;this.o.dispose();g.P.prototype.X.call(this);this.A=this.C=this.u=this.Ra=this.o=null};
g.h.AF=function(){this.oj(2)};
g.h.NK=function(){g8("Channel opened");this.M&&(this.M=!1,j8(this),this.J=g.so((0,g.w)(function(){g8("Timing out waiting for a screen.");this.oj(1)},this),15E3));
Vua(Qva(this.o),this.R)};
g.h.KK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.LK=function(a){q6();isNaN(this.kl())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,g8("Channel error: "+a+" with reconnection in "+this.kl()+" ms"),h8(this,2))};
g.h.MK=function(a){a.params?g8("Received: action="+a.action+", params="+g.sk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x6(a.params.devices);this.u=(0,g.ic)(a,function(c){return new d6(c)});
a=!!g.$a(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Jwa(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Jwa(this,!1);break;case "remoteConnected":var b=new d6(x6(a.params.device));g.$a(this.u,function(c){return c.rb(b)})||Dua(this.u,b);
break;case "remoteDisconnected":b=new d6(x6(a.params.device));g.ib(this.u,function(c){return c.rb(b)});
break;case "gracefulDisconnect":break;case "playlistModified":Lwa(this,a);break;case "nowPlaying":Nwa(this,a);break;case "onStateChange":Mwa(this,a);break;case "onAdStateChange":Owa(this,a);break;case "onVolumeChanged":Pwa(this,a);break;case "onSubtitlesTrackChanged":Kwa(this,a);break;case "nowAutoplaying":Qwa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.P("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Rwa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.xO=function(){if(this.w){var a=this.w;this.w=null;this.Ra.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.pF=function(){var a=3;this.ga()||(a=0,isNaN(this.kl())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.oj=function(a){g8("Disconnecting with "+a);i8(this);this.P("beforeDisconnect",a);1==a&&q6();Rva(this.o,a);this.dispose()};
g.h.oF=function(){var a=this.Ra;this.w&&(a=this.Ra.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.LO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Ra.videoId&&(this.w=b.videoId,g.uo(this.F),this.F=g.so((0,g.w)(this.xO,this),5E3));var c=[];this.Ra.listId==b.listId&&this.Ra.videoId==b.videoId&&this.Ra.index==b.index||c.push("remoteQueueChange");this.Ra.playerState==b.playerState&&this.Ra.volume==b.volume&&this.Ra.muted==b.muted&&V7(this.Ra)==V7(b)&&g.sk(this.Ra.o)==g.sk(b.o)||c.push("remotePlayerChange");this.Ra.reset(a);(0,g.x)(c,function(d){this.P(d)},this)};
g.h.Dx=function(){var a=this.o.C.id,b=g.$a(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.kl=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.h.dF=function(){return this.A||"UNSUPPORTED"};
g.h.eF=function(){return this.C||""};
g.h.DP=function(){if(!isNaN(this.kl())){var a=this.o.u;g.gn(a.o);a.start()}};
g.h.GO=function(a,b){l8(this,a,b);Iwa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.xh;f8.prototype.getProxyState=f8.prototype.pF;f8.prototype.disconnect=f8.prototype.oj;f8.prototype.getPlayerContextData=f8.prototype.oF;f8.prototype.setPlayerContextData=f8.prototype.LO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Dx;f8.prototype.getReconnectTimeout=f8.prototype.kl;f8.prototype.getAutoplayMode=f8.prototype.dF;f8.prototype.getAutoplayVideoId=f8.prototype.eF;f8.prototype.reconnect=f8.prototype.DP;
f8.prototype.sendMessage=f8.prototype.GO;g.r(m8,m7);g.h=m8.prototype;g.h.ne=function(a){return this.Ed.$_gs(a)};
g.h.contains=function(a){return!!this.Ed.$_c(a)};
g.h.get=function(a){return this.Ed.$_g(a)};
g.h.start=function(){this.Ed.$_st()};
g.h.add=function(a,b,c){this.Ed.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ed.$_r(a,b,c)};
g.h.lq=function(a,b,c,d){this.Ed.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.u.length;a<b;++a)this.Ed.$_ubk(this.u[a]);this.u.length=0;this.Ed=null;m7.prototype.X.call(this)};
g.h.HP=function(){this.P("screenChange")};
g.h.gM=function(){this.P("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.IP;v7.prototype.$_gsppc=v7.prototype.mD;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.lq;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.ne;v7.prototype.$_gos=v7.prototype.lD;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.xh;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.A);g.h=G8.prototype;
g.h.X=function(){g.A.prototype.X.call(this);this.A.stop();this.C.stop();this.M.stop();this.T();this.o.unsubscribe("proxyStateChange",this.gB,this);this.o.unsubscribe("remotePlayerChange",this.sm,this);this.o.unsubscribe("remoteQueueChange",this.Ap,this);this.o.unsubscribe("autoplayUpNext",this.xA,this);this.o.unsubscribe("previousNextChange",this.cB,this);this.o.unsubscribe("nowAutoplaying",this.XA,this);this.o.unsubscribe("autoplayDismissed",this.wA,this);this.o=this.B=null};
g.h.vz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":$7(this.o).Ya()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Lx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.HK=function(a){this.M.wF(a)};
g.h.iP=function(a){this.vz("control_subtitles_set_track",g.y.isEmpty(a)?null:a)};
g.h.xC=function(){var a=this.u.getOption("captions","track");g.y.isEmpty(a)||K8(this,a)};
g.h.MA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.sm,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.V.start();this.o.subscribe("remotePlayerChange",this.sm,this)}};
g.h.EL=function(){g.y.isEmpty(this.F)||cxa(this,this.F);this.G=!1};
g.h.gB=function(a,b){this.C.stop();2==b&&this.wC()};
g.h.sm=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.cC(8));this.vC();break;case 1085:case 3:I8(this,new g.cC(9));break;case 1083:case 0:I8(this,new g.cC(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.cC(4));break;case 2:I8(this,new g.cC(4));H8(this,V7(a));
break;case -1:I8(this,new g.cC(64));break;case -1E3:I8(this,new g.cC(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,cxa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.V.isActive()||this.XC()}else bxa(this)};
g.h.cB=function(){this.u.P("mdxpreviousnextchange")};
g.h.Ap=function(){J8(this)||bxa(this)};
g.h.rE=function(){this.o.Pw()};
g.h.xA=function(){};
g.h.XA=function(a){isNaN(a)||this.u.P("mdxnowautoplaying",a)};
g.h.wA=function(){this.u.P("mdxautoplaycanceled")};
g.h.rI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.XC=function(){if(J8(this)){var a=$7(this.o);this.w.Va(this.R);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.R=this.w.L(this.u,"onVolumeChange",this.MA)}};
g.h.vC=function(){this.A.stop();if(!this.o.ga()){var a=$7(this.o);a.Ya()&&I8(this,new g.cC(8));H8(this,V7(a));this.A.start()}};
g.h.wC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.Q);M8.prototype.Zb=function(){this.u.show()};
M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.Q);N8.prototype.A=function(a){exa(this,a.state)};g.r(O8,g.GN);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.wb(a,this.B,this),g.IN(this,(0,g.ic)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Ge(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.Ze=function(a){return"cast-selector-receiver"==a?"Cast...":this.C[a].name};
O8.prototype.ld=function(a){g.GN.prototype.ld.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.Za()};g.r(P8,g.KK);g.h=P8.prototype;
g.h.create=function(){Wwa(g.fy(this.player.N()));this.A.push(g.zo("yt-remote-before-disconnect",this.EK,this));this.A.push(g.zo("yt-remote-connection-change",this.LM,this));this.A.push(g.zo("yt-remote-receiver-availability-change",this.eB,this));this.A.push(g.zo("yt-remote-auto-connect",this.JM,this));this.A.push(g.zo("yt-remote-receiver-resumed",this.IM,this));this.A.push(g.zo("mdx-privacy-popup-confirm",this.jO,this));this.A.push(g.zo("mdx-privacy-popup-cancel",this.iO,this));this.eB()};
g.h.load=function(){this.player.cancelPlayback();g.KK.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=axa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.V=a||0,this.player.P("progresssync",a,void 0));dxa(this,this.F,this.F);g.nS(this.player.app,6)};
g.h.unload=function(){this.player.P("mdxautoplaycanceled");this.w=this.u;g.pe(this.B,this.o);this.o=this.B=null;g.KK.prototype.unload.call(this);g.nS(this.player.app,5);Q8(this)};
g.h.X=function(){g.Ao(this.A);g.KK.prototype.X.call(this)};
g.h.Pl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.vz.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.rF=function(){return this.loaded?this.B.suggestion:null};
g.h.Ry=function(){return this.o?$7(this.o).J:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.V};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Tc():!a.isAdPlaying()&&this.player.Tc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.w?a.A+T7(a):a.A,isAtLiveHead:1>=(a.w?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.w?a.u+T7(a):a.u,seekableStart:0<a.B?a.B+T7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.NG=function(){this.o&&this.o.jD()};
g.h.EK=function(a){1==a&&(this.R=this.o?$7(this.o):null)};
g.h.LM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.R=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.oe(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.R)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.P("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.eB=function(){this.J=[this.u].concat(Ywa());var a=y8()||this.u;R8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.bO=function(a){!this.M&&g.pC(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.JM=function(){var a=y8();R8(this,a)};
g.h.IM=function(){this.w=y8()};
g.h.jO=function(){this.M=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.iO=function(){this.M=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Qc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.OG=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Pf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.ZK.remote=P8;})(_yt_player);
